### ISSUE TITLE
[BUG]: cannot import name 'with_user_agent_extra' from 'databricks.sdk.core'

### ISSUE THREAD

**Issue by CedricEdouardKassi** [databrickslabs/ucx#2102]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello,
Following a Unity Catalog migration, I'm trying to migrate local groups with UCX. 
But, I get the following error message when running the Workflows migrate-groups(task verify_metastore_attached run): 

> File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.11/site-packages/databricks/labs/blueprint/__init__.py:1
> ----> 1 from databricks.sdk.core import with_user_agent_extra
>       3 from .__about__ import __version__
>       5 with_user_agent_extra("blueprint", __version__)
> 
> ImportError: cannot import name 'with_user_agent_extra' from 'databricks.sdk.core' (/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.11/site-packages/databricks/sdk/core.py)

Do you have a solution? Thanks in advance for your help.

### Cloud

Azure

### Operating System

macOS

### Version

latest via Databricks CLI

### Relevant log output

```shell
ImportError: cannot import name 'with_user_agent_extra' from 'databricks.sdk.core' (/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.11/site-packages/databricks/sdk/core.py)
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
File ~/.ipykernel/1937/command--1-3279393622:18
     15 entry = [ep for ep in metadata.distribution("databricks_labs_ucx").entry_points if ep.name == "runtime"]
     16 if entry:
     17   # Load and execute the entrypoint, assumes no parameters
---> 18   entry[0].load()()
     19 else:
     20   import importlib

File /usr/lib/python3.11/importlib/metadata/__init__.py:201, in EntryPoint.load(self)
    196 """Load the entry point from its definition. If only a module
    197 is indicated by the value, return that module. Otherwise,
    198 return the named object.
    199 """
    200 match = self.pattern.match(self.value)
--> 201 module = import_module(match.group('module'))
    202 attrs = filter(None, (match.group('attr') or '').split('.'))
    203 return functools.reduce(getattr, attrs, module)

File /usr/lib/python3.11/importlib/__init__.py:126, in import_module(name, package)
    124             break
    125         level += 1
--> 126 return _bootstrap._gcd_import(name[level:], package, level)

File <frozen importlib._bootstrap>:1206, in _gcd_import(name, package, level)

File <frozen importlib._bootstrap>:1178, in _find_and_load(name, import_)

File <frozen importlib._bootstrap>:1128, in _find_and_load_unlocked(name, import_)

File <frozen importlib._bootstrap>:241, in _call_with_frames_removed(f, *args, **kwds)

File <frozen importlib._bootstrap>:1206, in _gcd_import(name, package, level)

File <frozen importlib._bootstrap>:1178, in _find_and_load(name, import_)

File <frozen importlib._bootstrap>:1149, in _find_and_load_unlocked(name, import_)

File <frozen importlib._bootstrap>:690, in _load_unlocked(spec)

File <frozen importlib._bootstrap_external>:940, in exec_module(self, module)

File <frozen importlib._bootstrap>:241, in _call_with_frames_removed(f, *args, **kwds)

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.11/site-packages/databricks/labs/ucx/__init__.py:1
----> 1 from databricks.labs.blueprint.logger import install_logger
      3 install_logger()

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.11/site-packages/databricks/labs/blueprint/__init__.py:1
----> 1 from databricks.sdk.core import with_user_agent_extra
      3 from .__about__ import __version__
      5 with_user_agent_extra("blueprint", __version__)

ImportError: cannot import name 'with_user_agent_extra' from 'databricks.sdk.core' (/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.11/site-packages/databricks/sdk/core.py)
```

**Comment by ouranos** [comment]
I have the same issue after updating from v0.27.1 to v0.28.0
I can no longer run any commands:

```bash
➜  databricks-ucx databricks labs ucx -p stg-admin validate-groups-membership
[UPGRADE ADVISED] Newer ucx version was released 3 days ago. Please run `databricks labs upgrade ucx` to upgrade: v0.27.1 -> v0.28.0
12:05:59  INFO [d.l.u.workspace_access.groups] Listing workspace groups (resource_type=WorkspaceGroup) with id,displayName,meta,externalId,members,roles,entitlements...
12:06:01  INFO [d.l.u.workspace_access.groups] Found 4 WorkspaceGroup
12:06:01  INFO [d.l.u.workspace_access.groups] Listing account groups with id,displayName,externalId...
12:06:01  INFO [d.l.u.workspace_access.groups] Found 3 account groups
12:06:01  INFO [d.l.u.workspace_access.groups] No group listing provided, all matching groups will be migrated
12:06:02  INFO [d.l.u.workspace_access.groups] There are groups with different membership between account and workspace
Workspace Group Name  Members Count  Account Group Name  Members Count  Difference
engineering           0              engineering         1              -1
data-scientists       1              data-scientists     0              1
➜  databricks-ucx databricks labs upgrade ucx
Traceback (most recent call last):
  File "~/.databricks/labs/ucx/lib/src/databricks/labs/ucx/install.py", line 27, in <module>
    from databricks.sdk.core import with_user_agent_extra
ImportError: cannot import name 'with_user_agent_extra' from 'databricks.sdk.core' (~/.databricks/labs/ucx/state/venv/lib/python3.11/site-packages/databricks/sdk/core.py)
Error: installer: exit status 1
➜  databricks-ucx databricks labs ucx -p stg-admin validate-groups-membership
Traceback (most recent call last):
  File "~/.databricks/labs/ucx/lib/src/databricks/labs/ucx/cli.py", line 12, in <module>
    from databricks.labs.ucx.config import WorkspaceConfig
  File "~/.databricks/labs/ucx/lib/src/databricks/labs/ucx/__init__.py", line 1, in <module>
    from databricks.sdk.core import with_user_agent_extra, with_product
ImportError: cannot import name 'with_user_agent_extra' from 'databricks.sdk.core' (~/.databricks/labs/ucx/state/venv/lib/python3.11/site-packages/databricks/sdk/core.py)
Error: exit status 1
```

**Comment by ouranos** [comment]
I've managed to fix it by reinstalling with:
```bash
rm -rf ~/.databricks/labs/ucx
databricks labs install ucx
```

**Comment by ericvergnaud** [comment]
@ouranos @CedricEdouardKassi if this is fixed by reinstalling, would you mind closing this ticket ?

**Comment by k-scherer** [comment]
I also had this problem after running the `databricks labs upgrade ucx` command from v0.27.1 to v0.28.0

**Comment by ericvergnaud** [comment]
@k-scherer was it solved by reinstalling from scratch after `rm -rf ~/.databricks/labs/ucx` ?

**Comment by nfx** [comment]
issue is solved
